resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
- envs:
  - aws.properties
  name: aws-config

images:
- name: controller
  newName: controller
  newTag: local
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
